feat Newsletter component + implemented Mailchimp backend
hoffmann-ai/website pull request #11
Opened 2021-06-29 10:17 UTC by EliottElek

## Description
feat Newsletter component + implemented Mailchimp backend (yarn only)

2021-06-29 13:12 UTC, AlexHff requested changes

2021-06-29 13:12 UTC, AlexHff commented on src/components/Newsletter/Newsletter.js
> +      });
You shouldn't print anything to the console

2021-06-30 09:11 UTC, AlexHff commented on src/components/Newsletter/Newsletter.js
> +        setEmail('');
Que fait la fonction setEmail() ?
Pourquoi l'avoir appelé dans les deux situations ?

2021-06-30 14:43 UTC, dextmorgn commented on src/components/Newsletter/Newsletter.js
> +        setEmail('');
SetEmail() change le champ 'value' du input. Lorsque l'utilisateur appuie sur s'abonner, si l'opération s'est bien passée la valeur repasse à ' ', sinon l'utilisateur est averti que l'opération s'est mal déroulée.
La fonction est appelée dans les deux cas mais ce qu'elle retourne est différent.

2021-06-30 19:14 UTC, AlexHff commented on src/components/Newsletter/Newsletter.js
> +        setEmail('');
Je ne comprends pas pourquoi setter l'adresse mail s'il y a un problème. Est-ce qu'il ne faudrait pas set le `validationMessage` ?

2021-06-30 20:51 UTC, EliottElek commented on src/components/Newsletter/Newsletter.js
> +        setEmail('');
Effectivement c'est une meilleure idée; je vais plutôt faire ça.

2021-07-01 11:30 UTC, AlexHff commented on src/components/Newsletter/Newsletter.js
> +        setEmail('');
Tu peux entièrement retirer la fonction `then()`, elle n'est pas nécessaire. Le `catch()` reste intéressant.

2021-07-02 07:29 UTC, AlexHff approved these changes

2021-07-02 07:30 UTC, merged