Article mailchimp
hoffmann-ai/website pull request #12
Opened 2021-06-30 16:56 UTC by EliottElek

## Description 
created article on mailchimp usage.

2021-06-30 19:49 UTC, AlexHff requested changes

2021-06-30 19:49 UTC, AlexHff commented on src/components/Layout/Layout.js
> +import Navbar from '../Navbar/Navbar';
Revert this change, wrong branch.

2021-07-01 08:35 UTC, zoecrouzet commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +description: "Si vous souhaitez regrouper les données de votre audience et communiquer facilement avec celle-ci, intégrer une newsletter à votre site n'est pas une mauvaise idée. Heureusement pour no
"Heureusement pour vous" au lieu de "nous", sinon ça ne va pas trop avec la phrase d'avant

2021-07-01 08:39 UTC, zoecrouzet commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Si vous souhaitez regrouper les données de votre audience et communiquer facilement avec celle-ci, intégrer une newsletter à votre site n'est pas une mauvaise idée. Heureusement pour nous, la tâche n
"Heureusement pour vous" au lieu de "nous", sinon ça ne va pas trop avec la phrase d'avant

2021-07-01 11:32 UTC, AlexHff commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Si vous souhaitez regrouper les données de votre audience et communiquer facilement avec celle-ci, intégrer une newsletter à votre site n'est pas une mauvaise idée. Heureusement pour nous, la tâche n
Il faudra également modifier la description de l'article dans ce cas. Je pense qu'on peut trouver une phrase d'introduction (qui sert également de meta-description) un peu plus descriptive de l'article. Il faut y retrouver tous les mots clés car c'est une information qui est récupérée par Google pour le référencement.

2021-07-02 19:01 UTC, EliottElek commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Si vous souhaitez regrouper les données de votre audience et communiquer facilement avec celle-ci, intégrer une newsletter à votre site n'est pas une mauvaise idée. Heureusement pour nous, la tâche n
C'est toujours en cours ou le nouveau titre qui commence par "le guide ultime" convient ?

2021-07-02 19:29 UTC, AlexHff commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Si vous souhaitez regrouper les données de votre audience et communiquer facilement avec celle-ci, intégrer une newsletter à votre site n'est pas une mauvaise idée. Heureusement pour nous, la tâche n
Le titre est bon, la description est à revoir selon moi.

2021-07-06 07:43 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Mailchimp, c'est une plateforme qui offre des services de marketing diversifiés pour les petites et moyennes entreprises. L'un des principaux services proposés, et celui qui va nous intéresser aujour
"Mailchimp est une plateforme..."

2021-07-06 07:47 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Une autre possibilité implémentable très facilement est d'utiliser directement les extensions Mailchimp disponibles dans votre gestionnaire de plugins. Au moins 3 extensions s'offrent à vous : "MC4WP
"facilement implémentable est d'utiliser...."

2021-07-06 07:51 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Si vous travaillez sur un site statique avec Gatsby, la mission reste relativement simple. Il vous faut d'abord installer le plugin Mailchimp. Rendez-vous sur le terminal à la racine de votre projet,
"Commencez par installer le plugin Mailchimp. Ensuite, rendez-vous sur ..."

2021-07-06 07:58 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Vous devez ensuite entrer votre "endpoint". Le "endpoint" est un URL que vous pouvez retrouver sur votre admin Mailchimp, dans le code que nous trouvé dans <a href="#sur-wordpress">cette section</a>.
"Vous devez ensuite entrer votre "endpoint". Il s'agit d'un URL présent sur votre admin Mailchimp, dans le code trouvé au sein de <a href="#sur-wordpress">cette section</a>...."

2021-07-06 08:00 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Nous allons dans un premier temps créer un component ReactJS que l'on va appeler Newsletter. Dans mon dossier components, je crée un nouveau dossier Newsletter, dans lequel je vais créer un fichier `
"Nommé "Newsletter" " au lieu de "que l'on va appeler Newsletter"

2021-07-06 08:03 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Nous allons dans un premier temps créer un component ReactJS que l'on va appeler Newsletter. Dans mon dossier components, je crée un nouveau dossier Newsletter, dans lequel je vais créer un fichier `
"mais le résultat serait le même en utilisant les classes" au lieu de "mais vous aurez le même résultat si vous utilisez les classes"

2021-07-06 08:04 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Puis l'on crée un component Newsletter que l'on va exporter:
"Puis on crée" au lieu de "puis l'on"

2021-07-06 08:05 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Ensuite, il faut créer le module en JSX. Ici, rien de bien compliqué : la fonction return doit retourner une seule balise "div", dans laquelle se trouve une balise "form" (formulaire). Dans cette bal
guillemets à "s'abonner"

2021-07-06 08:07 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +La partie front-end est terminée. Maintenant, intéressons-nous au développement du back-end. D'abord, nous allons créer un hook qui va permettre de mettre à jour notre variable "email" qui correspond
"Nous allons d'abord créer ..."
"notre variable "email" correspondant à l'email ..."

2021-07-06 08:07 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +On crée également un second hook qui va permettre d'actualiser le message, qui est vide au début :
"vide au début" au lieu de "qui est vide au debut"

2021-07-06 08:12 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Parfait, nous arrivons à récupérer l'email de l'utilisateur et le stocker dans une variable. Maintenant, lorsque l'utilisateur soumet son email, il faut qu'il soit ajouté à notre liste d'emails dans
"et à le stocker"
"A présent, lorsque l'utilisateur..." au lieu de "Maintenant..."
"(moment où l'utilisateur appuie sur "s'abonner")" au lieu de "(lorsque l'utilisateur aura appuyé sur "s'abonner")"

2021-07-06 08:19 UTC, Ines-ux-dev commented on content/posts/2021-30-06---Ajouter-une-newsletter-facilement-avec-Mailchimp.md
> +Nous allons choisir "Regular" pour débuter, mais libre à vous d'utiliser l'un des nombreux templates à votre disposition. Ensuite, il faut donner un nom à votre campagne. Je vais l'appeler "premier m
"Le mail sera envoyé à toute votre audience" au lieu de "Le mail sera envoyé à votre audience entière"

2021-07-10 17:05 UTC, AlexHff commented
@EliottElek il y a des modifs à effectuer

2021-07-10 17:11 UTC, AlexHff commented
@EliottElek il y a des modifs à effectuer

2021-07-11 11:40 UTC, AlexHff commented
Supprimer toutes les instances de "je" et les remplacer par "nous" ou bien par la forme passive.

2021-07-12 10:22 UTC, AlexHff requested changes

2021-07-12 10:22 UTC, AlexHff commented on src/components/Layout/Layout.js
> +import Navbar from '../Navbar/Navbar';
up!

2021-07-14 06:42 UTC, AlexHff commented on qq
> +  tabs-module[m
What's this?

2021-07-24 07:23 UTC, closed without merging