Remove latin articles
hoffmann-ai/website pull request #19
Opened 2021-07-07 08:52 UTC by Ines-ux-dev

## Description

## Related Issues

2021-07-07 08:54 UTC, AlexHff commented
@Ines-ux-dev as-tu supprimé les images associées aux articles ?

2021-07-09 10:19 UTC, AlexHff requested changes

2021-07-09 10:19 UTC, AlexHff commented on content/about.md
> -socialImage: "/media/image-2.jpg"
`socialImage` is an important metadata for search engines, you can't remove the image. Either change the image to something more relevant or keep the old one. In any case, you need to keep the `socialImage`.

2021-07-09 10:19 UTC, AlexHff commented on content/contact.md
> -socialImage: "/media/image-4.jpg"
Same comment here.

2021-07-10 16:37 UTC, AlexHff requested changes

2021-07-10 16:37 UTC, AlexHff commented on content/about.md
> +template: "page"
remove whitespace

2021-07-10 16:37 UTC, AlexHff commented on content/contact.md
> +template: "page"
remove whitespace at the end of line

2021-07-10 16:38 UTC, AlexHff commented
Il reste deux articles qui n'ont pas été supprimés. As-tu ouvert le projet en local ?

2021-07-12 07:30 UTC, Ines-ux-dev commented
![](https://github.trello.services/images/mini-trello-icon.png) [[HOFFMANN.AI] Remove sample articles](https://trello.com/c/KHDQ6tI8/59-hoffmannai-remove-sample-articles)

2021-07-12 14:40 UTC, merged